(() => {
const M=globalThis.AdvancedModel,$=id=>document.getElementById(id),fmt=(v,d=3)=>v.toFixed(d);
let lang='zh',kind='multi',features=[...M.fruitPrototypes[0]],axisX=0,axisY=1,selectedCategory=0,outputMode='single',prompt=0,prefix=[...M.languagePrompts[0]],generated=[],mode='greedy',timer=null;
const t=(zh,en)=>lang==='zh'?zh:en;
const names=()=>[t('重量','Weight'),t('甜度','Sweetness'),t('含水量','Water content'),t('硬度','Firmness')];
const categories=()=>[t('橙子','Orange'),t('柚子','Pomelo'),t('苹果','Apple')];
const tags=()=>[t('甜','Sweet'),t('多汁','Juicy'),t('偏硬','Firm')];
function stop(){clearInterval(timer);timer=null;if($('decode-auto'))$('decode-auto').textContent=t('自动生成','Auto-generate');}
function reset(which){stop();kind=which;features=[...M.fruitPrototypes[0]];axisX=0;axisY=1;selectedCategory=0;outputMode='single';prompt=0;prefix=[...M.languagePrompts[0]];generated=[];mode='greedy';}
function render(which,language){stop();kind=which;lang=language;which==='multi'?renderMulti():renderDecode();}
function renderMulti(){
 $('advanced-lessons').innerHTML=`<div class="workspace">
 <section class="card"><div class="card-top"><h3><span class="section-number">01</span>${t('一个水果，四条信息','One fruit, four measurements')}</h3></div><div class="label-buttons">${categories().map((name,i)=>`<button class="secondary" data-fruit-preset="${i}">${name}</button>`).join('')}</div>${names().map((name,i)=>`<div class="parameter"><div class="parameter-title"><label for="feature-${i}">${name}</label><output id="feature-value-${i}"></output></div><input id="feature-${i}" type="range" min="0" max="1" step="0.01" value="${features[i]}"></div>`).join('')}</section>
 <section class="card"><div class="card-top"><h3><span class="section-number">02</span>${t('让输出回答不同问题','Ask different questions')}</h3></div><div class="label-buttons"><button id="mode-single" class="secondary">${t('品种：三选一','Variety: choose one')}</button><button id="mode-multi" class="secondary">${t('特征：可多选','Traits: multiple labels')}</button></div><div id="multi-output"></div><p id="multi-output-note" class="chart-foot"></p></section>
 <section class="card"><div class="card-top"><h3><span class="section-number">03</span>${t('信息怎样穿过神经网络','How information flows through the network')}</h3></div><div id="multi-network" class="chart"></div><p class="chart-foot">${t('调整输入，观察节点亮度和输出概率。切换上方问题，查看对应的输出连接。','Adjust an input to see node activity and output probabilities change. Switch the question above to see its output connections.')}</p></section>
 <section class="card"><div class="card-top"><h3><span class="section-number">04</span>${t('高维数据的一扇窗口','A window into higher dimensions')}</h3></div><div class="projection-selectors">${['x','y'].map((axis,i)=>`<label>${axis.toUpperCase()}<select id="projection-${axis}">${names().map((name,j)=>`<option value="${j}" ${j===(i?axisY:axisX)?'selected':''}>${name}</option>`).join('')}</select></label>`).join('')}</div><div id="multi-projection" class="chart"></div><p class="chart-foot">${t('图里只显示两维；网络始终使用全部四维。圆圈是当前输入：选样本时沿用品种颜色，自定义时使用预测品种的颜色。','Only two dimensions are shown; the network always uses all four. The ring matches the selected fruit’s variety; custom inputs use the predicted variety’s color.')}</p></section>
 </div><section class="card probability-explanation"><div class="card-top"><h3><span class="section-number">05</span>${t('多个输入，不等于只能有一个答案','Several inputs can answer several questions')}</h3></div><div class="mse-stages"><div><strong>${t('多维输入','Multidimensional input')}</strong><p>${t('每一维是一条信息。二维图只是挑出两条来画，重叠的点不一定是相同的水果。','Each dimension is a measurement. A 2D view displays just two; overlapping points can still describe different fruits.')}</p></div><div><strong>${t('多分类：同一个问题的多个选项','Multiclass: alternatives to one question')}</strong><p>${t('品种在三个类别中选一个。三个概率共享 100%；提高一个，其他的总份额就减少。这一步叫 Softmax。','Choose one of three varieties. Their probabilities share 100%; more for one leaves less for the others. This is Softmax.')}</p></div><div><strong>${t('多标签：多个独立的问题','Multilabel: separate questions')}</strong><p>${t('甜吗？多汁吗？偏硬吗？每个标签各自使用 Sigmoid，可以同时成立，概率不需要相加等于 100%。这里以 50% 为显示阈值。','Sweet? Juicy? Firm? Each label uses its own Sigmoid, so several can apply at once. Their probabilities need not sum to 100%. Here labels above 50% are displayed as present.')}</p></div></div><p class="chart-foot">${t('测量值均缩放到 0–1；本关使用固定示例权重和合成水果，重点观察信息怎样影响输出。','Measurements are scaled to 0–1. This lesson uses fixed illustrative weights and synthetic fruits to explore how inputs affect outputs.')}</p></section>`;
 for(let i=0;i<4;i++)$('feature-'+i).oninput=()=>{features[i]=+$('feature-'+i).value;selectedCategory=null;updateMulti();};
 document.querySelectorAll('[data-fruit-preset]').forEach(b=>b.onclick=()=>{selectedCategory=+b.dataset.fruitPreset;features=[...M.fruitPrototypes[selectedCategory]];updateMulti();});
 $('mode-single').onclick=()=>{outputMode='single';updateMulti();};$('mode-multi').onclick=()=>{outputMode='multi';updateMulti();};
 for(const axis of ['x','y'])$('projection-'+axis).onchange=()=>{if(axis==='x'){axisX=+$('projection-x').value;if(axisX===axisY)axisY=(axisX+1)%4;}else{axisY=+$('projection-y').value;if(axisY===axisX)axisX=(axisY+1)%4;}$('projection-x').value=axisX;$('projection-y').value=axisY;updateMulti();};
 updateMulti();
}
function updateMulti(){
 const colors=['#26466b','#9b4146','#7b8174'];
 const prediction=M.fruitPrediction(features),single=outputMode==='single',values=single?prediction.categories:prediction.labels,labels=single?categories():tags();
 features.forEach((v,i)=>{$('feature-'+i).value=v;$('feature-value-'+i).textContent=fmt(v,2);});
 $('mode-single').setAttribute('aria-pressed',String(single));$('mode-multi').setAttribute('aria-pressed',String(!single));
 const best=values.indexOf(Math.max(...values));
 $('multi-output').innerHTML=values.map((p,i)=>`<div class="output-row" data-output="${i}" data-probability="${p}"><div><strong style="color:${colors[i]}">${labels[i]}</strong><span>${fmt(p*100,1)}%</span></div><div class="output-track"><span style="width:${p*100}%;background:${colors[i]}"></span></div><small>${single?(i===best?t('最可能','Most likely'):''):(p>=.5?t('标签成立','Label present'):t('未达阈值','Below threshold'))}</small></div>`).join('');
 $('multi-output-note').textContent=single?t('三个概率相加 = 100%；选择概率最大的类别。','The three probabilities sum to 100%; select the most likely class.'):t('每个概率独立。一个水果可以既甜、又多汁、又偏硬。','Each probability is independent. A fruit can be sweet, juicy and firm at the same time.');

 const samples=M.fruitSamples(),X=v=>42+v*385,Y=v=>224-v*192;let svg='';
 for(let i=0;i<=4;i++){const v=i/4;svg+=`<path d="M42 ${Y(v)} H427 M${X(v)} 32 V224" stroke="#e5e4df" fill="none"/><text x="${X(v)}" y="241" text-anchor="middle" font-size="10" fill="#666764">${v}</text><text x="33" y="${Y(v)+3}" text-anchor="end" font-size="10" fill="#666764">${v}</text>`;}
 samples.forEach((sample,i)=>{svg+=`<circle data-fruit-point="${i}" tabindex="0" role="button" aria-label="${categories()[sample.category]} ${i+1}" cx="${X(sample.features[axisX])}" cy="${Y(sample.features[axisY])}" r="4" fill="${colors[sample.category]}" opacity=".7"/>`;});
 svg+=`<circle id="current-fruit" cx="${X(features[axisX])}" cy="${Y(features[axisY])}" r="7" fill="none" stroke="${colors[selectedCategory??prediction.categories.indexOf(Math.max(...prediction.categories))]}" stroke-width="2.5" pointer-events="none"/><text x="42" y="17" font-size="12" fill="#666764">${names()[axisY]}</text><text x="427" y="258" text-anchor="end" font-size="12" fill="#666764">${names()[axisX]}</text>`;
 $('multi-projection').innerHTML=`<svg viewBox="0 0 460 265" role="group" aria-label="${t('水果数据的二维投影','Two-dimensional fruit projection')}">${svg}</svg><div class="projection-legend">${categories().map((name,i)=>`<span style="color:${colors[i]}">● ${name}</span>`).join('')}</div>`;
 document.querySelectorAll('[data-fruit-point]').forEach(el=>{const choose=()=>{selectedCategory=samples[+el.dataset.fruitPoint].category;features=[...samples[+el.dataset.fruitPoint].features];updateMulti();};el.onclick=choose;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};});
 const hidden=features.flatMap(v=>[v,1-v]),iy=i=>64+i*62,hy=i=>42+i*31,oy=i=>80+i*78;
 const weights=single?[[0,2.4,.6,0,2,0,-1.2,0],[4,0,-.8,0,1.2,0,-.5,0],[0,1.7,.4,0,-1.3,0,2.5,0]]:[[0,0,8,0,0,0,0,0],[0,0,0,0,8,0,0,0],[0,0,0,0,0,0,8,0]];
 let network=`<text x="88" y="17" text-anchor="middle">${t('四项输入','4 inputs')}</text><text x="224" y="17" text-anchor="middle">${t('隐藏层','Hidden layer')}</text><text x="370" y="17" text-anchor="middle">${single?'Softmax':'Sigmoid'}</text>`;
 hidden.forEach((v,j)=>{network+=`<path d="M100 ${iy(Math.floor(j/2))} L214 ${hy(j)}" stroke="#26466b" opacity=".24" ${j%2?'stroke-dasharray="4 3"':''}/>`;});
 weights.forEach((row,i)=>row.forEach((w,j)=>{if(w)network+=`<path d="M234 ${hy(j)} L352 ${oy(i)}" stroke="${colors[i]}" opacity="${.12+.4*hidden[j]}" ${w<0?'stroke-dasharray="4 3"':''}/>`;}));
 features.forEach((v,i)=>{network+=`<text x="68" y="${iy(i)+4}" text-anchor="end">${names()[i]}</text><circle cx="88" cy="${iy(i)}" r="12" fill="#26466b" fill-opacity="${.12+.88*v}"/><text x="88" y="${iy(i)+27}" text-anchor="middle">${fmt(v,2)}</text>`;});
 hidden.forEach((v,j)=>{network+=`<circle data-hidden-activity="${v}" cx="224" cy="${hy(j)}" r="10" fill="#26466b" fill-opacity="${.12+.88*v}"/>`;});
 values.forEach((p,i)=>{network+=`<circle cx="366" cy="${oy(i)}" r="14" fill="${colors[i]}" fill-opacity="${.15+.85*p}"/><text x="388" y="${oy(i)+4}" fill="${colors[i]}">${labels[i]}</text><text x="366" y="${oy(i)+32}" text-anchor="middle" fill="${colors[i]}">${fmt(p*100,1)}%</text>`;});
 $('multi-network').innerHTML=`<svg viewBox="0 0 460 300" role="img" aria-label="${t('四个输入、八个隐藏神经元和三个输出','Four inputs, eight hidden neurons and three outputs')}" style="font-size:11px;fill:#666764">${network}</svg>`;

}
function tokenText(token){return M.tokenLabels[lang][token];}
function renderDecode(){
 $('advanced-lessons').innerHTML=`<section class="card decode-toolbar"><label>${t('从一句话开始','Start with a prompt')}<select id="decode-prompt">${[t('今天的天气…','Today’s weather…'),t('晴天的计划','A sunny-day plan'),t('雨天的计划','A rainy-day plan')].map((name,i)=>`<option value="${i}" ${i===prompt?'selected':''}>${name}</option>`).join('')}</select></label><label>${t('选择下一个词','Choose the next token')}<select id="decode-mode"><option value="greedy" ${mode==='greedy'?'selected':''}>${t('总选最可能的','Always most likely')}</option><option value="sample" ${mode==='sample'?'selected':''}>${t('按概率抽取','Sample by probability')}</option></select></label><div class="train-row"><button id="decode-step" class="primary">${t('生成一个词','Generate one token')}</button><button id="decode-auto" class="secondary">${t('自动生成','Auto-generate')}</button><button id="decode-undo" class="secondary">${t('退回一步','Undo a step')}</button></div></section>
 <div class="decoding-flow"><section class="card"><div class="card-top"><h3><span class="section-number">01</span>${t('已有文字','Text so far')}</h3></div><div id="decode-prefix" class="decode-prefix"></div><p id="decode-state" class="chart-foot" role="status"></p></section><div class="decode-blackbox"><span aria-hidden="true">→</span><div class="black-box">${t('神经网络','Neural network')}</div><span aria-hidden="true">→</span></div><section class="card"><div class="card-top"><h3><span class="section-number">02</span>${t('下一个词的概率','Next-token probabilities')}</h3></div><div id="decode-options"></div></section></div>
 <div class="feedback-loop">↶ ${t('选择一个 → 接到文字后面 → 整段文字重新成为输入','Choose one → append it → feed the whole text back in')}</div>
 <div class="decode-explain-grid"><section class="card"><div class="card-top"><h3>Tokenizer · ${t('把文字变成编号','Text becomes IDs')}</h3></div><p class="chart-foot">${t('Tokenizer（分词器）把文字拆成 token，再按词表映射为编号。token 可以是字、词的一部分、词或标点，不一定是完整的词。','A tokenizer splits text into tokens and maps them to vocabulary IDs. A token may be a character, part of a word, a word, or punctuation.')}</p><div id="decode-tokenizer"></div><p class="chart-foot">${t('这里沿用教学用的词与短语划分，编号是示意词表 ID。编号只标识 token，不表示大小或含义；进入网络后会转换成向量。','This demo uses predefined word and phrase chunks with illustrative vocabulary IDs. IDs identify tokens; their magnitudes carry no meaning. They are converted into vectors inside the network.')}</p></section><section class="card"><div class="card-top"><h3>${t('从输入序列到下一个 token','From a sequence to the next token')}</h3></div><div id="decode-network" class="decode-network"></div><p class="chart-foot">${t('左侧每个节点代表一个输入位置；右侧每个节点代表一个候选 token 的概率。网络内部统一用方框表示，省略向量与内部结构；右侧仅展开本例非零概率的候选项。','Each left node represents an input position; each right node represents a candidate token probability. The box abstracts vectors and internal architecture. Only candidates with nonzero probability in this demo are shown.')}</p></section></div>
 <section class="card"><div class="card-top"><h3><span class="section-number">03</span>${t('这段话是怎样长出来的','How the text grows')}</h3></div><div id="decode-history"></div></section>
 <section class="card probability-explanation"><div class="card-top"><h3><span class="section-number">04</span>${t('每一步都是一次分类','Each step is a classification')}</h3></div><div class="mse-stages"><div><strong>${t('输出是一张概率表','A distribution, not a whole sentence')}</strong><p>${t('所有候选词是类别，概率加起来为 100%。网络一次只回答：接下来可能是什么？','Candidate tokens are the classes and their probabilities sum to 100%. The network answers only: what might come next?')}</p></div><div><strong>${t('自己生成的文字，继续作为输入','Generated text becomes new input')}</strong><p>${t('选出的词接回原文，再预测下一个。换一个选择，后面的概率和句子就可能走向不同方向。试着比较晴天和雨天的计划。','Append the chosen token and predict again. A different choice can change later probabilities and the resulting text. Compare the sunny and rainy plans.')}</p></div><div><strong>${t('最可能，不是唯一可能','Most likely is not the only possibility')}</strong><p>${t('总选第一名更稳定；按概率抽取会产生不同结果。遇到结束标记就停止，而不是不停地写下去。','Picking the top candidate is predictable. Sampling can produce different results. An end marker tells the loop to stop.')}</p></div></div><p class="chart-foot">${t('为看清循环，本关使用小词表与预设的上下文概率模拟神经网络的输出，并非通用语言模型。每块表示一个词或短语；真实系统的 token 也不一定是完整的词。','This small vocabulary and preset context-dependent distribution illustrate the loop; they are not a general-purpose language model. Each block is a word or phrase; real tokens need not be whole words either.')}</p></section>`;
 $('decode-prompt').onchange=()=>{stop();prompt=+$('decode-prompt').value;prefix=[...M.languagePrompts[prompt]];generated=[];updateDecode();};
 $('decode-mode').onchange=()=>{mode=$('decode-mode').value;};
 $('decode-step').onclick=()=>{stop();generateOne();};
 $('decode-auto').onclick=()=>{if(timer){stop();return;}if(!M.nextTokenOptions(prefix).length)return;timer=setInterval(generateOne,900);$('decode-auto').textContent=t('暂停','Pause');};
 $('decode-undo').onclick=()=>{stop();if(generated.length){generated.pop();prefix.pop();updateDecode();}};
 updateDecode();
}
function appendToken(item){prefix.push(item.token);generated.push({...item});if(item.token==='eos')stop();updateDecode();}
function generateOne(){const options=M.nextTokenOptions(prefix),choice=M.chooseToken(options,mode);if(choice)appendToken(choice);else stop();}
function updateDecode(){
 const options=M.nextTokenOptions(prefix),ended=!options.length,initial=M.languagePrompts[prompt].length;
 updateDecodeDiagrams(options);
 $('decode-prefix').innerHTML=prefix.map((token,i)=>`<span class="token ${i>=initial?'generated-token':''} ${i===prefix.length-1&&i>=initial?'latest-token':''}">${token==='eos'?t('〈结束〉','〈End〉'):tokenText(token)}</span>`).join(lang==='en'?' ':'');
 $('decode-state').textContent=ended?t('收到结束标记，生成完成。','End marker received. Generation complete.'):t(`已生成 ${generated.length} 步 · 点击候选词也可以决定下一步。`,`${generated.length} steps generated · You can also choose a candidate directly.`);
 $('decode-options').innerHTML=options.length?options.map(item=>`<button class="candidate" data-token="${item.token}" data-token-probability="${item.p}"><span>${item.token==='eos'?t('〈结束〉','〈End〉'):tokenText(item.token)}</span><div class="output-track"><span style="width:${item.p*100}%"></span></div><strong>${fmt(item.p*100,0)}%</strong></button>`).join(''):`<p>${t('这句话已经结束。可以退回一步，或换一个开头再试。','This sentence has ended. Undo a step or choose another prompt.')}</p>`;
 $('decode-step').disabled=ended;$('decode-auto').disabled=ended;$('decode-undo').disabled=!generated.length;
 document.querySelectorAll('[data-token]').forEach(button=>button.onclick=()=>{stop();appendToken(options.find(item=>item.token===button.dataset.token));});
 $('decode-history').innerHTML=generated.length?`<div class="decode-history">${generated.map((item,i)=>`<div><small>${String(i+1).padStart(2,'0')}</small><span>${tokenText(item.token)}</span><strong>${fmt(item.p*100,0)}%</strong></div>`).join('')}</div>`:`<p>${t('先生成一个词，看看它如何成为下一轮输入的一部分。','Generate a token and watch it become part of the next input.')}</p>`;
}
function updateDecodeDiagrams(options){
 const vocabulary=Object.keys(M.tokenLabels.zh),id=token=>vocabulary.indexOf(token),label=token=>token==='eos'?t('〈结束〉','〈End〉'):tokenText(token);
 $('decode-tokenizer').innerHTML=`<div class="tokenizer-source">${prefix.map(label).join(lang==='en'?' ':'')}</div><div class="tokenizer-arrow">↓ Tokenizer</div><div class="tokenizer-pairs">${prefix.map(token=>`<div><span>${label(token)}</span><span aria-hidden="true">↓</span><code>${id(token)}</code></div>`).join('')}</div><div class="tokenizer-arrow">↓ ${t('按原顺序组成输入序列','Input sequence in original order')}</div><div class="tokenizer-ids">[${prefix.map(id).join(', ')}]</div>`;
 const h=Math.max(280,80+prefix.length*36),y=(i,n)=>60+(h-100)*(i+.5)/n;
 let svg=`<defs><marker id="decode-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill="#8794a3"/></marker></defs><text x="96" y="23" text-anchor="middle">${t('输入序列','Input sequence')}</text><text x="386" y="23" text-anchor="middle">${t('下一个词的概率','Next-token probabilities')}</text><rect x="174" y="56" width="130" height="${h-86}" rx="8" fill="#26466b"/><text x="239" y="${h/2+10}" text-anchor="middle" fill="white" font-size="16">${t('神经网络','Neural network')}</text>`;
 prefix.forEach((token,i)=>{const cy=y(i,prefix.length);svg+=`<text x="106" y="${cy+4}" text-anchor="end">${label(token)}</text><circle data-input-position="${i}" cx="133" cy="${cy}" r="13" fill="#edf1f5" stroke="#26466b"/><text x="133" y="${cy+4}" text-anchor="middle" font-size="10">${id(token)}</text><path d="M146 ${cy} H172" stroke="#8794a3" marker-end="url(#decode-arrow)"/>`;});
 options.forEach((item,i)=>{const cy=y(i,options.length);svg+=`<path d="M304 ${cy} H331" stroke="#8794a3" marker-end="url(#decode-arrow)"/><circle data-output-probability="${item.p}" cx="348" cy="${cy}" r="14" fill="#26466b" fill-opacity="${.15+.85*item.p}" stroke="#26466b"/><text x="374" y="${cy-3}">${label(item.token)}</text><text x="374" y="${cy+15}" fill="#9b4146">${fmt(item.p*100,0)}%</text>`;});
 if(!options.length)svg+=`<text x="386" y="${h/2}" text-anchor="middle">${t('已结束','Complete')}</text>`;
 $('decode-network').innerHTML=`<svg viewBox="0 0 490 ${h}" role="img" aria-label="${t('输入序列节点经过神经网络方框，输出下一个词的概率节点','Input sequence nodes pass through a neural network box to next-token probability nodes')}">${svg}</svg>`;
}
globalThis.AdvancedLessons={reset,render,stop};
})();
